[package]
name = "r2rcon-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rrplug = { git = "https://github.com/R2NorthstarTools/rrplug.git" }
once_cell = "1.18.0"
log = "0.4.19"
parking_lot = "0.12.1"
thiserror = "1.0.44"

[build-dependencies]
windres = "0.2.2"

[lib]
crate-type = ["cdylib"]
